#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')


# In[2]:


df=pd.read_csv('C:\\Users\\Ishwarya\\Downloads\\heart.csv')


# In[3]:


df.head()


# In[4]:


df.tail()


# In[5]:


df.columns.values


# In[6]:


df.isna().sum()


# In[7]:


df.info()


# In[8]:


df.hist(bins = 50,grid = False, figsize = (20,15));


# In[9]:


df.describe()


# In[10]:


questions = ["1.How many people have heart disease and how many people doesn't have heart disease?",
            "2.people of which sex has most heart disease",
            "3.people of which sex has which type of cheat pain most?",
            "4.people with which chest pain are most pron to have heart diesease?"]

questions


# In[11]:


df.target.value_counts()


# In[12]:


df.target.value_counts().plot(kind ='bar',color=["orchid","salmon"])
plt.title("Heart Disease value")
plt.xlabel("1=Heart Disease,0=No heart Disease")
plt.ylabel("Amount");


# In[14]:


df.target.value_counts().plot(kind ='pie',figsize=(8,6))
plt.legend(["Disease","No disease"]);


# In[15]:


df.sex.value_counts()


# In[16]:


#plotting a pie chart
df.sex.value_counts().plot(kind= 'pie',figsize = (8,6))
plt.title('Male Female ratio')
plt.legend(['Male','Female']);


# In[20]:


pd.crosstab(df.target,df.sex)


# In[22]:


df.cp.value_counts()


# In[23]:


df.cp.value_counts().plot(kind='bar',color=['salmon','lightskyblue','springgreen','khaki'])
plt.title('chest pain type vs count');


# In[31]:


pd.crosstab(df.sex,df.cp)


# In[35]:


pd.crosstab(df.sex, df.cp).plot(kind= 'bar', color = ['coral','lightskyblue','plum','khaki'])
plt.title('Type of chest pain for sex')
plt.xlabel('0=Female,  1=Male');


# In[39]:


pd.crosstab(df.cp,df.target)


# In[40]:


sns.countplot(x= 'cp',data = df, hue = 'target');


# In[41]:


sns.displot( x = 'age',data = df , bins = 30,kde = True);


# In[42]:


sns.displot( x = 'thalach',data = df , bins = 30,kde = True,color='chocolate');


# In[ ]:




