#!/usr/bin/env python
# coding: utf-8

# In[10]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime


# In[11]:


data = pd.read_csv('C:\\Users\\Ishwarya\\Downloads\\householdtask3.csv')


# In[4]:


display(data.head(10))


# In[12]:


plt.scatter(data['year'],data['own'])
plt.title("scatter plot")
plt.xlabel('year')
plt.ylabel('own')
plt.show()


# In[7]:


plt.plot(data['year'])
plt.plot(data['own'])


plt.title("Line chart")
plt.xlabel('year')
plt.ylabel('own')
plt.show()


# In[13]:


plt.bar(data['year'],data['own'])

plt.title("Bar plot")
plt.xlabel('year')
plt.ylabel('own')
plt.show()


# In[9]:


#Histogram
plt.hist(data['income'])

plt.title("Histogram")
plt.show()


# In[ ]:




